environment:

  matrix:
    - PYTHON: "C:\\Miniconda"
      PYTHON_VERSION: "2.7.11"
      TESTENVS: "py27-pyqt4"

init:
  - "ECHO %PYTHON% %PYTHON_VERSION% %PYTHON_ARCH% %APPVEYOR_REPO_TAG_NAME%"

install:
  # dump version
  - git describe --tags --always
  # install cython for building lupa
  - pip install cython
  # install and build Lua
  - git clone http://luajit.org/git/luajit-2.0.git
  - cd luajit-2.0
  - git describe --tags --always
  - "\"%LOCALAPPDATA%\\Programs\\Common\\Microsoft\\Visual C++ for Python\\9.0\\vcvarsall.bat\" x86"
  - cd src
  - msvcbuild
  - cd ../..
  # build lupa
  - "%PYTHON%\\python setup.py bdist_msi"

artifacts:
  - path: '**\*.msi'
  - path: '**\*.whl'
  - path: '**\*.exe'

deploy:
  - provider: GitHub
    release: $(appveyor_build_version)
    auth_token:
      secure: "09WRxoB8lu9lPzuk3qYu0brKVQubLpnsS1Wdn49nYZYi5RDiva3z37eITcjtZkTD"
    artifact: /.*\.msi/
    draft: true
    prerelease: true
    on:
      appveyor_repo_tag: true

build: off
