environment:

  matrix:
    - PYTHON: "C:\\Miniconda"
      PYTHON_VERSION: "2.7.11"
      TESTENVS: "py27-pyqt4"

init:
  - "ECHO %PYTHON% %PYTHON_VERSION% %PYTHON_ARCH% %APPVEYOR_REPO_TAG_NAME%"

install:
  # dump version
  - git describe --tags --always
  # install and build Lua
  - git clone https://github.com/LuaDist/lua.git
  - git -C lua describe --tags --always
  - mkdir lua-build
  - cd lua-build
  - "\"%LOCALAPPDATA%\\Programs\\Common\\Microsoft\\Visual C++ for Python\\9.0\\vcvarsall.bat\" x86"
  - cmake -G "NMake Makefiles" ../lua
  - nmake
  - cd ..
  # build lupa
  - "%PYTHON%\\python setup.py bdist_msi --global-option=build_ext --global-option=\"-I%APPVEYOR_BUILD_FOLDER%\\lua-build;%APPVEYOR_BUILD_FOLDER%\\lua\\src\" --global-option=\"-L%APPVEYOR_BUILD_FOLDER%\\lua-build\" --global-option=\"-lliblua_static\""

artifacts:
  - path: '**\*.msi'
  - path: '**\*.whl'
  - path: '**\*.exe'

deploy:
  - provider: GitHub
    release: $(appveyor_build_version)
    auth_token:
      secure: "09WRxoB8lu9lPzuk3qYu0brKVQubLpnsS1Wdn49nYZYi5RDiva3z37eITcjtZkTD"
    artifact: /.*\.msi/
    draft: true
    prerelease: true
    on:
      appveyor_repo_tag: true

build: off
